token: "<yourtoken>"
prefix: "&"
activity: "play.uniqsky.fr"
noPerm: "ğŸ˜‚"
reaction:
  valid: "UsValid:642724648517238785"
  invalid: "USnot_Valid:642724619454906378"
suggests:
  channels:
  - 639122530904571924
  - 638835318199681047
  title: "**Suggestion de *%user%***"
  message: "%message%"
  footer: 'Une suggestion? Ã‰crivez-la ici'
accept:
  command: "&accept"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  channel: 639122594112733204
  notfound: "â‰ï¸"
  footer: 'Cette suggestion a Ã©tÃ© acceptÃ©e, merci Ã  vous'
deny:
  command: "&deny"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  channel: 666661238444523580
  notfound: "â‰ï¸"
  footer: 'Cette suggestion a Ã©tÃ© refusÃ©e'
new:
  title: 'Nouveau membre ! ğŸ‰'
  channel: 638877412108533841
  name: 'Membre :'
  value: '%user%'
  footer: 'Nous sommes dÃ©sormais %number% membres'