token: "<yourtoken>"
prefix: "&"
activity: "https://uniqsky.fr"
noPerm: "üòÇ"
reaction:
  valid: "UsValid:642724648517238785"
  invalid: "USnot_Valid:642724619454906378"
suggests:
  channels:
  - 639122530904571924
  - 638835318199681047
  title: "**Suggestion de *%user%***"
  message: "%message%"
  footer: 'Une suggestion? √âcrivez-la ici'
accept:
  prefix: "&suggestaccept"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  channel: 639122594112733204
  notfound: "‚ÅâÔ∏è"
  footer: 'Cette suggestion a √©t√© accept√©e, merci √† vous'
  emoji:
    valid: "USapproved:666424091028226078"
    invalid: "USdeclined:666424122695221269"