token: "<yourtoken>"
prefix: "&"
activity: "play.uniqsky.fr"
noPerm: "ðŸ˜‚"
reaction:
  valid: "UsValid:642724648517238785"
  invalid: "USnot_Valid:642724619454906378"
help:
  command: "help"
  title: "Help"
  footer: "Made by 0ddlyoko and Grandoz for UniqSky"
  show:
    1:
      title: "Mods"
      values:
      - "`&accept <id>` - Accepter une suggestion"
      - "`&deny <id>` - Refuser une suggestion"
      - "`&clear <number>` - Clear des messages"
suggests:
  channels:
  - 639122530904571924
  - 638835318199681047
  title: "**Suggestion de *%user%***"
  message: "%message%"
  footer: 'Une suggestion? Ã‰crivez-la ici'
accept:
  command: "accept"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  - 392421161092513792
  channel: 639122594112733204
  notfound: "â‰ï¸"
  footer: 'Cette suggestion a Ã©tÃ© acceptÃ©e, merci Ã  vous'
deny:
  command: "deny"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  - 392421161092513792
  channel: 666661238444523580
  notfound: "â‰ï¸"
  footer: 'Cette suggestion a Ã©tÃ© refusÃ©e'
new:
  title: 'Nouveau membre ! ðŸŽ‰'
  channel: 638877412108533841
  name: 'Membre :'
  value: '%user%'
  footer: 'Nous sommes dÃ©sormais %number% membres'
playernumber:
  channel: 662421330502746112
  message: "ConnectÃ© : %number%/%maxnumber%"
chat:
  channel: 666391573805662220
  format: "> %pseudo%: %message%"
  mc: "&e[&6Discord&e] %user% &fâž¡ %message%"
  users:
    '1':
      id: 304694488394235924
      user: "&4[Admin] 0ddlyoko"
    '2':
      id: 520268695210295326
      user: "&4[Admin] babouchka_"
    '3':
      id: 392421161092513792
      user: "&4[Admin] EroTwiiix"
    '4':
      id: 243363049505816576
      user: "&2[Moderateur] LegLinx"
    '5':
      id: 294132448097337345
      user: "&2[Moderateur] GostPunk"
    '6':
      id: 414527363234398208
      user: "&2[Moderateur] Ameliiie"
    '7':
      id: 549306792417558539
      user: "&2[Moderateur] Ameliiie"
    '8':
      id: 222064468987740161
      user: "&2[Moderateur] Zetolution"
    '9':
      id: 593062067896844321
      user: "&a[Guide] 0_SkyWolfLee"
    '10':
      id: 229276095621365761
      user: "&a[Guide] Color4"
    '11':
      id: 363367264919093249
      user: "&a[Guide] Oropo_"
clear:
  command: "clear"
  allowUsers:
  - 304694488394235924
  - 520268695210295326
  - 392421161092513792
  - 414527363234398208
  - 294132448097337345
  - 222064468987740161